### PR TITLE
add check run url as an action output

### PR DESCRIPTION
**Pull request by Smuu**

### CODE REVIEW

**Review by shigupt202 — APPROVED** [review]

**Comment by Smuu** [comment]
Failed integration test not coming from my changes.

It seems that the integration script don't get the correct number of arguments.
See https://github.com/Azure/container-scan/runs/2746141236 and https://github.com/Azure/container-scan/blob/96b52e8d7dbd3e27911408133c21be347328d115/.github/workflows/integration-tests.yml#L19.

I suppose some variables/secrets are not set and therefore empty?

I also can see the token in the workflow output! I suggest to use environment variables here instead of script arguments.

**Comment by shigupt202** [comment]
@sundargs2000 Can you take a look at the failing test?

**Review by ds-ms — APPROVED** [review]
LGTM

**Comment by shigupt202** [comment]
Integration tests currently fail for PRs raised from forks, as confirmed by @sundargs2000. Merging this PR, and will raise one to port this to release/v0 where integration tests can also be triggered.

**Pull request merged**
