### PR TITLE
Support Trivy new JSON schema

### PR DESCRIPTION
**Pull request by knqyf263**
Fix https://github.com/Azure/container-scan/issues/104

### CODE REVIEW

**Comment by knqyf263** [comment]
```
$ curl -s https://api.github.com/user/2253692 | jq .login
"knqyf263"
```

My GitHub ID seems to be correct. I don't understand why CLA assistant is complaining about it.

**Comment by knqyf263** [comment]
I did it many times.

**Comment by ajinkya599** [comment]
Hey @knqyf263, We are working to resolve the CLA issue and it is unfortunately taking more time.
Are you okay if I send out a separate PR and make these changes to `main`? We have more PRs to follow.

**Comment by knqyf263** [comment]
>Are you okay if I send out a separate PR and make these changes to main? We have more PRs to follow.
Sure. It would be great if my contribution is merged somehow, but please feel free to close the issue.

**Comment by ajinkya599** [comment]
@knqyf263 I also wanted your contribution to be in but unfortunately this CLA issue is one-off and is taking longer.
That's why I wanted to check with you if you are okay with me taking this separately.

**Comment by knqyf263** [comment]
>That's why I wanted to check with you if you are okay with me taking this separately.

I'm ok with that.

**Comment by ajinkya599** [comment]
Ported via the other PR:
- https://github.com/Azure/container-scan/pull/114

**Pull request closed without merging**
